name: MADE Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  made-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install npm
      - name: Set up npm
        uses: actions/setup-node@v3

      - name: Install jayvee 
        run: 
          npm i -g @jvalue /jayvee-interpreter@0.2.0
               
      - name: Run MADE Pipeline
        run: 
            bash project/pipeline.sh 
