name: MADE Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  made-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         
              
      - name: Run MADE Pipeline
        run: 
            bash project/pipeline.sh 
